---

- name: Copy jenkins exporter script
  ansible.builtin.template:
    src: "jenkins_exporter"
    dest: /usr/local/bin/jenkins_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy jenkins exporter script
  ansible.builtin.template:
    src: "jenkins_exporter.service"
    dest: /etc/systemd/system/jenkins_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart jenkins exporter service is restarted
  ansible.builtin.service:
    name: Jenkins_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for jenkins exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ jenkins_exporter_server_bind }}"
    port: "{{ jenkins_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
