---
# handlers for ansible-role-docker-jenkins_exporter

- name: Restart jenkins_exporter
  ansible.builtin.service:
    name: Jenkins_exporter
    state: restarted
    enabled: true

- name: Start jenkins_exporter
  ansible.builtin.service:
    name: Jenkins_exporter
    state: started
    enabled: true

- name: Reload jenkins_exporter
  ansible.builtin.service:
    name: Jenkins_exporter
    state: reloaded
    enabled: true
